-- SCHEMA - LIST OF LOGICAL STRUCTURES OF DATA/A COLLECTION OF DATABASE OBJECTS (EX. TABLES)

CREATE TABLE candidates (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  industry_connected BOOLEAN NOT NULL
);

